security:
    password_hashers:
        App\Entity\Admin: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_admin_provider:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            lazy: true
            provider: app_admin_provider
            pattern: ^/admin
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: app_admin_dashboard
                username_parameter: email
                password_parameter: password
            logout:
                path: admin_logout
                target: admin_login                  # Redigire vers la page de connexion après déconnexion






    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            App\Entity\Admin:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
